name: Stars

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: kbrgl/star-readme@main
        with:
          token: ${{ secrets.GH_PAT }}
